---
- name: "Install Tmux"
  become: yes
  apt:
    name: tmux
    state: latest

- name: "Copy tmux config"
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}"
     
